### ISSUE TITLE
Please add a readme or test JS file so we can fork your repository as ibmcndev

### ISSUE THREAD

**Issue by ibmcndev** [GSchwede/FBConnectionsCustomization#1]
Hi,
In order for us to fork your repository it needs to have some content. Please add a readme or test JavaScript file. Also if possible, could you give your repository a more meaningful name so it can be distinguished more easily in the "ibmcnxdev" organization e.g SchwedeCustomizerSamples, SchwedeCustomizations or if your customization has a specific purpose then something like "ActivityStreamUpdater". 

Thanks,
ibmcndev team

**Comment by GSchwede** [comment]
Hi, I have added a readme and several files to the repository. Sorry, pretty new at all of this.. 

Thanks, 
Gunnar
